# Generated by Django 4.0.2 on 2022-03-30 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.CharField(blank=True, max_length=255, null=True)),
                ('proposal_status', models.CharField(blank=True, choices=[('Delivered', 'Delivered'), ('Executed', 'Executed'), ('Pricing', 'Pricing')], max_length=255, null=True)),
                ('proposal_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('proposal_amount', models.FloatField(blank=True, null=True)),
                ('item_type', models.CharField(blank=True, max_length=255, null=True)),
                ('no_items', models.CharField(blank=True, max_length=255, null=True)),
                ('item_details', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('es_width', models.FloatField(blank=True, null=True)),
                ('es_height', models.FloatField(blank=True, null=True)),
                ('fn_width', models.FloatField(blank=True, null=True)),
                ('fn_height', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_proposal', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update_proposal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
