# Generated by Django 4.0.2 on 2022-03-30 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_type', models.CharField(blank=True, max_length=255, null=True)),
                ('no_items', models.CharField(blank=True, max_length=255, null=True)),
                ('item_details', models.CharField(blank=True, max_length=255, null=True)),
                ('fn_width', models.FloatField(blank=True, null=True)),
                ('fn_height', models.FloatField(blank=True, null=True)),
                ('task_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('task_status', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=255, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_task', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_project', to='projects.project')),
                ('project_manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_pj_manager_employee', to=settings.AUTH_USER_MODEL)),
                ('sales_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_sales_employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
